export const LOAD_DATA = 'LOAD_DATA';
export const SEARCH_SET_SEARCHSTRING = 'SEARCH_SET_SEARCHSTRING';
export const SEARCH_SET_SEARCHSORT = 'SEARCH_SET_SEARCHSORT';
export const SEARCH_SET_SEARCHORDER = 'SEARCH_SET_SEARCHORDER';
export const SEARCH_RESULT_STATUS = 'SEARCH_RESULT_STATUS';