export const PULL_UP_VISIBLE = "PULL_UP_VISIBLE";
export const PULL_UP_SET_TITLE = "PULL_UP_SET_TITLE";
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_SET_MESSAGE = 'NOTIFICATION_SET_MESSAGE';
